dat<-read.table('Data/household_power_consumption.txt', header = TRUE ,sep = ";")
subdat<- subset(dat,dat$Date %in% c("1/2/2007", "2/2/2007"))
subdat$Global_active_power <- as.numeric(subdat$Global_active_power)
png("plot1.png", width=480, height=480)
hist(subdat$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()